### ISSUE TITLE
relevant paper

### ISSUE THREAD

**Issue by kannabu** [Yuki-11/NTIRE2023_ShadowRemoval_IIM_TTI#1]
Hello ,is there a relevant paper for this code?Thank you!

**Comment by Yuki-11** [comment]
Thank you for your interest in our work!

Here is a summary paper of the NTIRE Challenge provided by the organizers. However, it contains few details of our methodology.

https://openaccess.thecvf.com/content/CVPR2023W/NTIRE/papers/Vasluianu_NTIRE_2023_Image_Shadow_Removal_Challenge_Report_CVPRW_2023_paper.pdf

`@inproceedings{vasluianu2023ntire,
  title={NTIRE 2023 image shadow removal challenge report},
  author={Florin-Alexand ru Vasluianu and Tim Seizinger and Radu Timofte and Shuhao Cui and Junshi Huang and Shuman Tian and Mingyuan Fan and Jiaqi Zhang and Li Zhu and Xiaoming Wei and Xiaolin Wei and Ziwei Luo and Fredrik K. Gustafsson and Zheng Zhao and Jens Sjölund and Thomas B. Schön and Xiaoyi Dong and Xi Sheryl Zhang and Chenghua Li and Cong Leng and Woon-Ha Yeo and Wang-Taek Oh and Yeo-Reum Lee and Han-Cheol Ryu and Jinting Luo and Chengzhi Jiang and Mingyan Han and Qi Wu and Wenjie Lin and Lei Yu and Xinpeng Li and Ting Jiang and Haoqiang Fan and Shuaicheng Liu and Shuning Xu and Binbin Song and Xiangyu Chen and Shile Zhang and Jiantao Zhou and Zhao Zhang and Suiyi Zhao and Huan Zheng and Yangcheng Gao and Yanyan Wei and Bo Wang and Jiahuan Ren and Yan Luo and Yuki Kondo and Riku Miyata and Fuma Yasue and Taito Naruki and Norimichi Ukita and Hua-En Chang and Hao-Hsiang Yang and Yi-Chung Chen and Yuan-Chun Chiang and Zhi-Kai Huang and Wei-Ting Chen and I-Hsiang Chen and Chia-Hsuan Hsieh and Sy-Yen Kuo and Li Xianwei and Huiyuan Fu and Chunlin Liu and Huadong Ma and Binglan Fu and Huiming He and Mengjia Wang and Wenxuan She and Yu Liu and Sabari Nathan and Priya Kansal and Zhongjian Zhang and Huabin Yang and Yan Wang and Yanru Zhang and Shruti S. Phutke and Ashutosh Kulkarni and MD Raqib Khan and Subrahmanyam Murala and Santosh Kumar Vipparthi and Heng Ye and Zixi Liu and Xingyi Yang and Songhua Liu and Yinwei Wu and Yongcheng Jing and Qianhao Yu and Naishan Zheng and Jie Huang and Yuhang Long and Mingde Yao and Feng Zhao and Bowen Zhao and Nan Ye and Ning Shen and Yanpeng Cao and Tong Xiong and Weiran Xia and Dingwen Li and Shuchen Xia},
  booktitle={CVPRW},
  year={2023}
}`

The technical report detailing our methodology is here. The article will be published on Friday, March 15, 2024 at 00:00:00 GMT. We will add the URL here as soon as it is published.

`@article{kondo2023ntire,
  title={NTIRE 2023 Image Shadow Removal Challenge Technical Report: Team IIM_TTI},
  author={Yuki Kondo, Riku Miyata, Fuma Yasue, Taito Naruki, Norimichi Ukita}
  journal={arXiv},
  year={2024}
}`

Warm Regards,

**Comment by Yuki-11** [comment]
Our paper has been published on arXiv! And, the pdf file uploaded here has been deleted.
https://arxiv.org/abs/2403.08995

**Comment by kannabu** [comment]
Thank you for your enthusiastic reply, I wish you all the best in your work, and help you have fun every day!

**Comment by kannabu** [comment]
Thank you for your enthusiastic reply, I wish you all the best in your work and a good mood every day!

**Comment by Yuki-11** [comment]
@kannabu 
Thank you! I wish you success too!
